import 'dart:io' as io;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:provider/provider.dart';
import 'package:weatherapp/core/app/app_config.dart';
import 'package:weatherapp/models/dailyForecast.dart';
import 'package:weatherapp/models/weatherDataset.dart';
import 'package:weatherapp/providers/global/config/config_provider.dart';
import 'package:weatherapp/widgets/forecastAccordion.dart';

import '../_http_overrides.dart';

// Mock data
DailyForecast forecast = DailyForecast(
  tempMin: 0.0,
  tempMax: 5.0,
  datasets: <WeatherDataset>[
    WeatherDataset(
      description: "clear sky",
      icon: "01n",
      lon: 139,
      lat: 35,
      name: "Shuzenij",
      temp: 281.52,
      tempMin: 280.15,
      tempMax: 283.71,
      dateTime: DateTime.now(),
    )
  ],
);

void main() {
  setUp(() {
    // Only needs to be done once since the HttpClient generated by this
    // override is cached as a static singleton.
    io.HttpOverrides.global = new TestHttpOverrides();
  });

  testWidgets("ForecastAccordion displays current weekday.",
      (WidgetTester tester) async {
    ForecastAccordion accordion = ForecastAccordion(<DailyForecast>[forecast]);

    await tester.pumpWidget(MediaQuery(
      data: MediaQueryData(),
      child: MaterialApp(
        home: Builder(
          builder: (context) {
            return MultiProvider(
              providers: [
                Provider<ConfigProvider>(
                  create: (_) => ConfigProvider(ProdConfig()),
                ),
              ],
              child: Container(
                child: (SingleChildScrollView(
                  child: Column(children: [accordion]),
                )),
              ),
            );
          },
        ),
      ),
    ));

    await tester.pumpAndSettle();

    expect(find.text("Friday"), findsOneWidget);
  });
}
